### ISSUE TITLE
GeoGuessr_Resolver

### ISSUE THREAD

**Issue by grach1337** [0x978/GeoGuessr_Resolver#1]
competitive geogusser no work, pls fix i'ts

**Comment by Noirgluk** [comment]
@0x978 did you update?

**Comment by 0x978** [comment]
> @0x978 did you update?
> competitive geogusser no work, pls fix i'ts

This issue should now be resolved. For any further issues, please create a new Issue on github.
Please note there is also a new control scheme, see the in-game alert for more information.

If there is any further issues, please create a new issue in Github.
