### ISSUE TITLE
issue

### ISSUE THREAD

**Issue by MasterDucksOfChina** [0x978/GeoGuessr_Resolver#12]
1 4500- 5000 guess and 2 - perfect not working, everytime i click 1 or 2 it doesnt make an automatic  guess

**Comment by 0x978** [comment]
Yeah, things are broken atm.

Script is still usable for now if you press 4 to open in google maps. WIll look at fixing

**Comment by 0x978** [comment]
I got a solution out - all modes except streaks should work for now.

Let me know if there's any issues
