### ISSUE TITLE
doesnt work in country mode

### ISSUE THREAD

**Issue by Kiajajaj** [0x978/GeoGuessr_Resolver#14]
it works well in distance but it wont work in country after the update

**Comment by Kiajajaj** [comment]
and also someones it triggers the emoji shortcuts instead of the cheat like when i tap 1 it sends out an emoji

**Comment by 0x978** [comment]
> it works well in distance but it wont work in country after the update

Should be fixed now - use the latest version.


> and also someones it triggers the emoji shortcuts instead of the cheat like when i tap 1 it sends out an emoji

Nothing has changed here for it to stop working. You can disable emoji in game if it bothers you.
