### ISSUE TITLE
Tool keeps placing me in African water.

### ISSUE THREAD

**Issue by the2thomasklu8** [0x978/GeoGuessr_Resolver#18]
Occasionally, when I play using this tool, the marker is just placed in the middle of African water, about left of Gabon and below Ghana. The place on the equator where those directions meet.

What do I do?

**Comment by rikuddo91** [comment]
There definitely seems to be something up with the interception/update, sometimes it works for one map and for other it get stuck in the first map. It doesn't update the new coordinates along with the new map.
I've checked in Dev-Tools and can see the new coordinates but the script doesn't get those new coordinates,

**Comment by 0x978** [comment]
> There definitely seems to be something up with the interception/update function, sometimes it works for one map and for other it get stuck in the first map. It doesn't update the new coordinates along with the new map. I've checked in Dev-Tools and can see the new coordinates but the script doesn't get those new coordinates,

Unfortunately, since the game has become paid-to-play I can't update the script

**Comment by cnehm006** [comment]
> > There definitely seems to be something up with the interception/update function, sometimes it works for one map and for other it get stuck in the first map. It doesn't update the new coordinates along with the new map. I've checked in Dev-Tools and can see the new coordinates but the script doesn't get those new coordinates,
> 
> Unfortunately, since the game has become paid-to-play I can't update the script

Hey, would you be able to update the script if I gave you access to my account?

**Comment by 0x978** [comment]
> > > There definitely seems to be something up with the interception/update function, sometimes it works for one map and for other it get stuck in the first map. It doesn't update the new coordinates along with the new map. I've checked in Dev-Tools and can see the new coordinates but the script doesn't get those new coordinates,
> > 
> > 
> > Unfortunately, since the game has become paid-to-play I can't update the script
> 
> Hey, would you be able to update the script if I gave you access to my account?

Yeah, if this is something you are willing to do, contact me on discord @qhn

**Comment by cnehm006** [comment]
> > > > There definitely seems to be something up with the interception/update function, sometimes it works for one map and for other it get stuck in the first map. It doesn't update the new coordinates along with the new map. I've checked in Dev-Tools and can see the new coordinates but the script doesn't get those new coordinates,
> > > 
> > > 
> > > Unfortunately, since the game has become paid-to-play I can't update the script
> > 
> > 
> > Hey, would you be able to update the script if I gave you access to my account?
> 
> Yeah, if this is something you are willing to do, contact me on discord @qhn

shot u a message
