### ISSUE TITLE
Not working on competitive mode

### ISSUE THREAD

**Issue by uselessplayer1** [0x978/GeoGuessr_Resolver#2]
The script has now stopped working in competitive mode. Always shows a location near San Francisco.

**Comment by 0x978** [comment]
I see, for now this only seems to be happening in the duels gamemode. I will look into this

**Comment by uselessplayer1** [comment]
Thank you so much.

**Comment by uselessplayer1** [comment]
Are there any updates on this issue?

**Comment by 0x978** [comment]
> Are there any updates on this issue?

Sadly not yet, i have been busy with a lot of other work. Has this issue spread to any other gamemodes ?

**Comment by uselessplayer1** [comment]
I just checked. It works in streaks mode and in usual game mode. Still does not work in Duels.

**Comment by ThBanshee** [comment]
I came here to make the same comment; nice to see that you know of the issue.

**Comment by uselessplayer1** [comment]
Hi, are there any updates to the script?

**Comment by 0x978** [comment]
> Hi, are there any updates to the script?

I'm still too busy with University stuff, but it's on my todo list to look into.

The problem is that I will need to find a new method of reading the coordinates, which could take quite a while.

**Comment by 0x978** [comment]
> Hi, are there any updates to the script?
> I came here to make the same comment; nice to see that you know of the issue.
> The script has now stopped working in competitive mode. Always shows a location near San Francisco.

Hey, I believe I have fixed this now, and also added a new feature to open the location in google maps.

**Comment by uselessplayer1** [comment]
That's awesome. Thanks so much for the update. I will test this in the morning and let you know.

Much appreciated.
