### ISSUE TITLE
Remove detection script doesnt work

### ISSUE THREAD

**Issue by OpecenaPalacinka** [0x978/GeoGuessr_Resolver#28]
Brackets are missing as in script.remove call. Since the "remove" is a function? Like in the code below. 
Or am I wrong are they are not needed?

const scripts = document.querySelectorAll('script');
scripts.forEach(script => {
    if (script.id === "resolver-cheat-detection-script") {
        script.remove**()**
    }
});

**Comment by 0x978** [comment]
whoops, fixed.
