### ISSUE TITLE
Hi

### ISSUE THREAD

**Issue by TheNukeLuke** [0x978/GeoGuessr_Resolver#4]
I am currently working on a Chrome extension project that shares some similarities with your project. After researching various resources, I came across your code repository on GitHub and found it to be an excellent reference for my own development process.

While I have been able to make progress on my project by studying your code, I have reached a point where I am facing some challenges. Specifically, I am struggling with a particular section of the code that relates to enemy guesses and auto guess in competitive duels. 

I would like to know if you can help me finish this project.

**Comment by 0x978** [comment]
> I would like to know if you can help me finish this project.

Sure, feel free to add me on discord - username is qhn
