### ISSUE TITLE
Got banned

### ISSUE THREAD

**Issue by TheKerbecs** [0x978/GeoGuessr_Resolver#5]
Hi, i loaded in the script and got immediately banned from multiplayer. 
All it took was 1 game without any obvious guesses on my part.

**Comment by 0x978** [comment]
hm - I ran the script for 2 duels games, making really bait guesses and didn't get immediately banned.

Have you got banned before this ban? Perhaps they keep information about bans in cookies or something which caused you to get banned twice?

Even if not, try and do this again this for me on another account? Perhaps clear cookies / site data or use incognito mode?

**Comment by TheKerbecs** [comment]
that was a very fast response, thank you. 
i was never banned before and i have no clue if its a fault on my part or not.
what i did was: i played 1 multiplayer and went into party duels mode afterwards(i used it in both). there i was not able to make a guess, so i switched browsers but the same problem accrued. thats where i saw that i was banned.
 i have created a new account and will try it again in the next hours, then update you on the situation.

how high do you think my chances are on getting my ban appealed?

**Comment by 0x978** [comment]
Unban appeals are unlikely to be successful, I’m afraid.

It is worth a try though.

Usually you just get generic boilerplate messages saying they wont unban you and refuse to comment further on their anti cheat methods.

If other people report being banned so quickly, then there might be a problem.

**Comment by TheKerbecs** [comment]
I was not able to recreate it. I used it for a few days now without any problems. Sorry :/
