### ISSUE TITLE
Scripte doesn't load at all

### ISSUE THREAD

**Issue by rikuddo91** [0x978/GeoGuessr_Resolver#8]
Probably something changed on the backend, but the script isn't loading at all now. Tried it with multiple browsers but it isn't loading, neither any feature work in-game (single or multiplayer). The account isn't banned, if you wonder about that.
Could you please check it?

**Comment by 0x978** [comment]
Yea, can confirm. Will have a fix asap

**Comment by 0x978** [comment]
Fixed. Please refer to https://text.0x978.com/geoGuessr for info about anticheat
